### ISSUE TITLE
Support tooltips in plots

### ISSUE THREAD

**Issue by shortcipher3** [iterative/dvc-render#103]
The `fiftyone` tool has a great precision-recall curve which includes tooltips with the threshold for a given precision/recall.  It would be awesome to support tooltips and precision-recall curves are a common use case.

![pr_curve](https://user-images.githubusercontent.com/8680583/177818302-1fc4ff6d-6a17-4f85-9929-17acc575badb.png)

**Comment by daavoo** [comment]
LinearTemplate plots now include tooltips and the fields shown can be adjusted using a custom template (https://github.com/iterative/dvc-render/pull/99#issuecomment-1322625173)

**Comment by shortcipher3** [comment]
Any hints on how to include the threshold value along with the precision/recall values?  We want to be able to choose a threshold based on the precision/recall curve.

If others are following one "hack" I've seen is to make a plot with threshold on the x-axis and precision and recall on the y-axis.  I suppose the tooltip will give us the x value and both y values.  Still we are more used to reading a precision/recall curve.

**Comment by daavoo** [comment]
> Any hints on how to include the threshold value along with the precision/recall values? We want to be able to choose a threshold based on the precision/recall curve.

You can save this template (i.e.  to `custom_linear.json`):

<details>

<summary>Show template</summary>

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "title": "<DVC_METRIC_TITLE>",
    "width": 300,
    "height": 300,
    "mark": {
        "type": "line",
        "point": true,
        "tooltip": {"content": "data"}
    },
    "encoding": {
        "x": {
            "field": "<DVC_METRIC_X>",
            "type": "quantitative",
            "title": "<DVC_METRIC_X_LABEL>"
        },
        "y": {
            "field": "<DVC_METRIC_Y>",
            "type": "quantitative",
            "title": "<DVC_METRIC_Y_LABEL>",
            "scale": {
                "zero": false
            }
        },
        "color": {
            "field": "rev",
            "type": "nominal"
        }
    }
}
```

</details>

And reference it in the `dvc.yaml` and/or `dvc plots` commands:

 ```yaml
stages:
  train:
    cmd: python train.py
    plots:
      prc.json:
        template: custom_linear.json
        x: recall
        y: precision
 ```
 
 ```console
 $ dvc plots show prc.json --template custom_linear.json --x recall --y precision
 ```

The relevant change is the usage of `"tooltip": {"content": "data"}`, which shows [all fields in the underlying data](https://vega.github.io/vega-lite/docs/tooltip.html#data), whereas in the built-in template we use `"tooltip": true` which shows [all fields specified in the encoding](https://vega.github.io/vega-lite/docs/tooltip.html#encoding).

Let me know if this works for your use case @shortcipher3

**Comment by shortcipher3** [comment]
Looks promising @daavoo I've been trying to test out, but I am running into error with the latest `dvc` (2.38.1), I get `DVC failed to load some plots for following revisions: 'workspace'.`

**Comment by shortcipher3** [comment]
I got it working and I like it.

I have been plotting several pr curves together.  Before I could provide a list of y values and get them to show up.  Now that doesn't seem to be the case, I get:

```
# dvc plots show
ERROR: unexpected error - 'list' object has no attribute 'items'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

For reference my dvc.yaml is pretty simple
```
plots:
  - pr.csv:
      x: recall
      y: [precision_class1, precision_class2, precision_class3]
      title: precision-recall @ iou 0.5
      y_label: precision
      template: pr_curve_template.json
```

I tried a couple other variations which met with other errors:
```
plots:
  - pr.csv:
      x: recall
      y: 
        - precision_class1
        - precision_class2
        - precision_class3
      title: precision-recall @ iou 0.5
      y_label: precision
      template: pr_curve_template.json
```
Gave:
```
# dvc plots show
ERROR: unexpected error - 'list' object has no attribute 'items'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

And
```
plots:
  - pr.csv:
      x: recall
      y: 
        precision_class1
        precision_class2
        precision_class3
      title: precision-recall @ iou 0.5
      y_label: precision
      template: pr_curve_template.json
```
Gave
```
# dvc plots show
ERROR: Could not find provided field ('precision_class1 precision_class2 precision_class3') in data fields ('precision_class1, precision_class2, precision_class3, precision_class4, precision_class5, recall').
```

Any ideas?

**Comment by dberenbaum** [comment]
@shortcipher3 It's a regression that should be fixed in the next release (see https://github.com/iterative/dvc/pull/8703). 

If you have to make it work with 2.38.1, you should be able to do it like:

```yaml
plots:
  - 'precision-recall @ iou 0.5':
      x: recall
      y:
        pr.csv: [precision_class1, precision_class2, precision_class3]
      y_label: precision
      template: pr_curve_template.json
```

**Comment by shcheklein** [comment]
@dberenbaum @daavoo since it's quite common and powerful thing, should we include a higher level interface for this? or even always show all the values in the tooltip by default. It looks like a cool feature to me. wdyt?

**Comment by daavoo** [comment]
> or even always show all the values in the tooltip by default. It looks like a cool feature to me. wdyt?

Yes I agree we can show all. For some reason when I tried I had an older DVC version and the tooltip was including some noisy internal fields (`dvc_version_info`) but this is no longer the case in recent versions

**Comment by dberenbaum** [comment]
> even always show all the values

This is the only part I'm not sure about. I could have a fairly "wide" csv file and I don't know that it would make sense to show everything by default, but I think it all depends on the use case, so no strong opinion either way.

**Comment by shcheklein** [comment]
thanks @daavoo ! let's create a ticket to add an example with thresholds? (may be even include them in the example-get-started)

**Comment by shortcipher3** [comment]
I second @dberenbaum's comment.  I have some csv files that are "wide".  Having it be the default is good, but would be great to be able configure with a property in the `dvc.yaml`.

Either way I will likely be breaking up my some of my "wide" csvs into multiple smaller versions so reading the tooltip is less noisy.
